#!/bin/sh

current_workspace=$(swaymsg -p -t get_workspaces|grep focused|grep -o "[0-9]")

wn=""
wp=""

if [ "$1" = "window" ]; then
	wn="swaymsg workspace number $((current_workspace + 1))"
	wp="swaymsg workspace number $((current_workspace - 1))"
	category="swaymsg move container to workspace number"
	shift
else
	category="swaymsg workspace number"
fi

if [ "$1" = "next" ]; then
	test $current_workspace -eq 9 && exit 1
	$category $((current_workspace + 1));
	$wn;
elif [ "$1" = "prev" ]; then
	test $current_workspace -eq 1 && exit 1
	$category $((current_workspace - 1));
	$wp;
fi


