#!/usr/bin/env bash

VOLUME=$(pamixer --get-volume)

# function icon {
#     if [[   $VOLUME -ge 66 ]]; then echo '󰕾'
#     elif [[ $VOLUME -ge 33 ]]; then echo '󰖀'
#     elif [[ $VOLUME -ge 1  ]]; then echo '󰕿'
#     else echo '󰝟'
#     fi
# }

# function level {
#     echo $(pamixer --get-volume)21
# }

# function update {
#     ~/.config/eww/scripts/osd $(icon) $(level)
# }

down() {
  pamixer -d 5
}

up() {
  pamixer -i 5
}

playpause() {
  playerctl play-pause
}

mute() {
  muted="$(pamixer --get-mute)"
  if $muted; then
    pamixer -u
  else 
    pamixer -m
  fi
}

mic_mute() {
  mic_muted="$(pamixer --default-source --get-mute)"
  if $mic_muted; then
    pamixer --default-source -u
  else
    pamixer --default-source -m
  fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
  mic_mute) mic_mute;;
  playpause) playpause;;
esac
