#!/bin/bash

low_flag=0
crit_flag=0
vcrit_flag=0
full_flag=0

while true; do
    # Get battery status
    status=$(acpi -b | awk '{print $3}')
    cap=$(acpi -b | grep -P -o '[0-9]+(?=%)')

    if [ "$status" == "Discharging," ]; then
        if [ "$cap" -le 5 ] && [ "$vcrit_flag" -eq 0 ]; then
            zenity --info --title="Out Of Juice" --text="SHUTDOWN in 1 minute.." --timeout=20 --window-icon="/home/scelester/MyScripts/no_battery.png"
            paplay /home/scelester/MyScripts/power.mp3  # Play sound
            shutdown now
            vcrit_flag=1
            low_flag=1  # Ensure the low_flag is set to avoid duplicate alerts
            crit_flag=1
        elif [ "$cap" -le 10 ] && [ "$crit_flag" -eq 0 ]; then
            zenity --warning --title="CRITICAL level reached" --text="Plug-in that charger, I'm gonna die...." --timeout=20 --window-icon="/home/scelester/MyScripts/battery_10.png"
            paplay /home/scelester/MyScripts/power.mp3  # Play sound
            crit_flag=1
            low_flag=1  # Ensure the low_flag is set to avoid duplicate alerts
        elif [ "$cap" -le 20 ] && [ "$low_flag" -eq 0 ]; then
            zenity --warning --title="Battery LOW" --text="Find the charger, already.." --timeout=20 --window-icon="/home/scelester/MyScripts/battery_20.png"
            paplay /home/scelester/MyScripts/power.mp3  # Play sound
            low_flag=1
        fi
        full_flag=0  # Reset full_flag when discharging
    fi

    sleep 30  # Check every 30 seconds
done
